### ISSUE TITLE
Windows 11 Install - Unable to get Supabase Working

### ISSUE THREAD

**Issue by grabani** [mckaywrigley/chatbot-ui#1069]
Hi There,

Thank you for your efforts.

I am unable to get the supabase working.

1) Installed chatbot using npm:
```
npm install

> chatbot-ui@2.0.0 prepare
> husky install

husky - Git hooks installed

added 819 packages, and audited 820 packages in 47s

262 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

2) Install Docker Desktop on Windows

3) To install supasbase, I could not use the the document `brew install supabase/tap/supabase` command as I am on Windows. So I used:

`npm install -g supabase-cli

added 28 packages in 7s

1 package is looking for funding
  run `npm fund` for details`

4) Added supabase t PATH; namely:

`C:\Users\<Username>\AppData\Roaming\npm`

5) Then started supabase:

`C:\Users\Home\chatbot-ui>supabase-cli init`

`C:\Users\Home\chatbot-ui>supabase-cli start`
```
[+] Running 13/13
 ✔ Container supabase-mail                   Running                                                               0.0s
 ✔ Container supabase-imgproxy               Started                                                               0.9s
 ✔ Container supabase-vector                 Healthy                                                               1.0s
 ✔ Container supabase-db                     Healthy                                                               0.9s
 ✔ Container supabase-analytics              Healthy                                                               1.8s
 ✔ Container supabase-meta                   Started                                                              10.8s
 ✔ Container supabase-studio                 Started                                                               1.8s
 ✔ Container supabase-edge-functions         Started                                                              10.8s
 ✔ Container realtime-dev.supabase-realtime  Started                                                               1.4s
 ✔ Container supabase-kong                   Started                                                               1.5s
 ✔ Container supabase-rest                   Started                                                               2.7s
 ✔ Container supabase-auth                   Started                                                               1.5s
 ✔ Container supabase-storage                Started                                                               0.6s
STUDIO:   http://localhost:3000/
REST API: http://localhost:8000/rest/v1/
GraphQL:  http://localhost:8000/graphql/v1
Mail:     http://localhost:9000/
```

Then I get error:

```
20240108234540_setup.sql
  20240108234541_add_profiles.sql
  20240108234542_add_workspaces.sql
  20240108234543_add_folders.sql
  20240108234544_add_files.sql
  20240108234545_add_file_items.sql
  20240108234546_add_presets.sql
  20240108234547_add_assistants.sql
  20240108234548_add_chats.sql
  20240108234549_add_messages.sql
  20240108234550_add_prompts.sql
  20240108234551_add_collections.sql
C:\Users\Home\AppData\Roaming\npm\node_modules\supabase-cli\node_modules\pg\lib\client.js:526
          Error.captureStackTrace(err);
                ^

error: function graphql.rebuild_schema() does not exist
    at C:\Users\Home\AppData\Roaming\npm\node_modules\supabase-cli\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async migrateDatabaseUser (C:\Users\Home\AppData\Roaming\npm\node_modules\supabase-cli\dist\libs\database.js:145:9)
    at async Command.startSupabase (C:\Users\Home\AppData\Roaming\npm\node_modules\supabase-cli\dist\commands\start.js:14:5) {
  length: 216,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '629',
  routine: 'ParseFuncOrColumn'
}

Node.js v20.10.0
```

Any thoughts?

**Comment by mckaywrigley** [comment]
@grabani We just updated the docs to include Supabase's official instructions for Windows installation which should help!

**Comment by grabani** [comment]
Yes great - thank you @mckaywrigley

I may be mistaken, but the additional step of adding the `NEXT_PUBLIC_SUPABASE_ANON_KEY` to the `.env.local` was necessary (which is not called out in the "Local Quickstart" section).
