### ISSUE TITLE
docker logs error 

### ISSUE THREAD

**Issue by frogchou** [mckaywrigley/chatbot-ui#109]
> ai-chatbot-starter@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)
    at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)
    at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)
    at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)
    at async /app/node_modules/next/dist/server/next.js:159:31
    at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)
    at async /app/node_modules/next/dist/cli/next-start.js:118:9

**Comment by mckaywrigley** [comment]
Probably need to run the command and then run.
