### ISSUE TITLE
Failed to fetch `Inter` from Google Fonts.

### ISSUE THREAD

**Issue by mindcont** [mckaywrigley/chatbot-ui#116]
According to the recommended installation method, execute until ```npm run dev``` the error is reported
```css
[wio@openiot chatbot-ui]$ npm run build

> ai-chatbot-starter@0.1.0 build /home/wio/chatbot-ui
> next build


./components/Chat/Chat.tsx
56:6  Warning: React Hook useEffect has a missing dependency: 'scrollToBottom'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/Chat/ChatInput.tsx
68:6  Warning: React Hook useEffect has a missing dependency: 'textareaRef'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types
ReferenceError: AbortController is not defined
    at fetchCSSFromGoogleFonts (/home/wio/chatbot-ui/node_modules/next/dist/compiled/@next/font/dist/google/fetch-css-from-google-fonts.js:34:28)
    at nextFontGoogleFontLoader (/home/wio/chatbot-ui/node_modules/next/dist/compiled/@next/font/dist/google/loader.js:76:79)
    at /home/wio/chatbot-ui/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:72:99
    at async Span.traceAsyncFn (/home/wio/chatbot-ui/node_modules/next/dist/trace/trace.js:79:20)
Failed to compile.

pages/_app.tsx
`next/font` error:
Failed to fetch `Inter` from Google Fonts.


> Build failed because of webpack errors
info  - Creating an optimized production build .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ai-chatbot-starter@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ai-chatbot-starter@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wio/.npm/_logs/2023-03-24T09_58_25_870Z-debug.log


```

**Comment by mckaywrigley** [comment]
Might have to do an npm update. Haven't seen this yet so probably a local issue.

**Comment by pccai** [comment]
Upgrade Nodejs to 18.* is OK.

**Comment by ELHart05** [comment]
any solution?
