### ISSUE TITLE
PDF upload not working for Azure OpenAI

### ISSUE THREAD

**Issue by othmanelhoufi** [mckaywrigley/chatbot-ui#1192]
Hello,

Thanks for this great tool, it is indeed the best Chat UI I've tried so far!

Let's get to the problem at hand. When uploading a file the default embedding model used is only from OpenAI services even though I am connected to the Azure OpenAI services.

Here is the error:
```
Error: OpenAI API Key not found
    at checkApiKey (webpack-internal:///(rsc)/./lib/server/server-chat-helpers.ts:52:15)
    at POST (webpack-internal:///(rsc)/./app/api/retrieval/process/route.ts:31:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ohoufi/Projects/chatbot-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62591
 ✓ Compiled /chat/[chatid] in 437ms (4547 modules)
Error: OpenAI API Key not found
    at checkApiKey (webpack-internal:///(rsc)/./lib/server/server-chat-helpers.ts:52:15)
    at POST (webpack-internal:///(rsc)/./app/api/retrieval/process/route.ts:31:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ohoufi/Projects/chatbot-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62591
Error: OpenAI API Key not found
    at checkApiKey (webpack-internal:///(rsc)/./lib/server/server-chat-helpers.ts:52:15)
    at POST (webpack-internal:///(rsc)/./app/api/retrieval/process/route.ts:31:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ohoufi/Projects/chatbot-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62591
```

Looking down into the `route.ts` file located in the `retrieval` folder I can see that the logic behind sends requests to OpenAI or Local embedding models and not to the currently connected provider:
```
if (embeddingsProvider === "openai") {
      checkApiKey(profile.openai_api_key, "OpenAI")
    }

    let chunks: any[] = []

    if (embeddingsProvider === "openai") {
      const openai = new OpenAI({
        apiKey: profile.openai_api_key || "",
        organization: profile.openai_organization_id
      })

      const response = await openai.embeddings.create({
        model: "text-embedding-ada-002",
        input: userInput
      })

...
```

**Comment by mckaywrigley** [comment]
There's an open PR for this that I'll likely merge in the next 24hrs. Just need to get around to reviewing.

**Comment by mckaywrigley** [comment]
Just fixed! Azure embeddings now work - just set the embeddings deployment ID.
