### ISSUE TITLE
No clear how to deploy on Vercel

### ISSUE THREAD

**Issue by afern247** [mckaywrigley/chatbot-ui#1220]
I cloned the repo, deployed on vercel and now when I go to the url I get:

![image](https://github.com/mckaywrigley/chatbot-ui/assets/34192856/619c6c6f-6f9b-4d82-9f76-5d63b57e5245)

The logs says:

```
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3850701382'
}
```

and
```
Error: Your project's URL and Key are required to create a Supabase client!

Check your Supabase project's API settings to find these values

https://supabase.com/dashboard/project/_/settings/api
    at g (/var/task/.next/server/chunks/9989.js:1:157301)
    at j (/var/task/.next/server/chunks/4493.js:49:3737)
    at em (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226)
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
    at Array.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504)
    at stringify (<anonymous>)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134889)
    at eP (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135332)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132112)
    at listOnTimeout (node:internal/timers:569:17)
```

If I deploy locally I can get the values of supabase with `supabase status` but how do i get it on vercel?

**Comment by gijigae** [comment]
One way to do is, 

1) Setup a database in the [Supabase website](https://supabase.com/).

![image](https://github.com/mckaywrigley/chatbot-ui/assets/81459/a8d8965e-7559-4154-9b43-3575f326c5ee)

2) Update the relevant values on Vercel as shown in the image below. Hope it helps.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/81459/4f4cf3c8-d462-4f99-a13d-6644ddcd8e64)

**Comment by mckaywrigley** [comment]
Yeah you'll need to set up the backend on Supabase.

**Comment by afern247** [comment]
I got to the login part and put the DB info on the env. but it's not working:

![image](https://github.com/mckaywrigley/chatbot-ui/assets/34192856/9a3a7565-62fb-4fe6-a71e-455c0378dd96)

I get a 303 response

**Comment by mckaywrigley** [comment]
Move to the "Help" category in "Discussions"
