### ISSUE TITLE
Mistral not working on vercel

### ISSUE THREAD

**Issue by viraniaman94** [mckaywrigley/chatbot-ui#1231]
Getting this error in Vercel when trying to run any of the Mistral models:

```
SyntaxError: Unterminated string in JSON at position 22 (line 1 column 23) at (app/api/chat/mistral/route.ts:52:36) 
```

Request path

```
/api/chat/mistral
```

Not getting the same error when running locally (Macbook Air M1)

Tested OpenAI model (GPT4 Turbo), seems to be working fine on vercel

**Comment by xycjscs** [comment]
change fetch method to openai method （by setting baseurl）。it will solve this problem。

**Comment by mckaywrigley** [comment]
Fixed!

**Comment by viraniaman94** [comment]
Not sure if commenting here will reopen the issue, but now I am getting a new error while using Mistral on Vercel:

```
 Error: 400 status code (no body)
    at (node_modules/openai/error.mjs:40:19)
    at (node_modules/openai/core.mjs:248:24)
    at (node_modules/openai/core.mjs:287:29)
    at (app/api/chat/mistral/route.ts:27:21)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:189:36)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:128:25)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:251:29)
    at (node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:81:20)
    at (node_modules/next/dist/esm/server/web/adapter.js:157:15) {
  status: 400,
  headers: {
  access-control-allow-origin: '*',
  cf-as-number: '16509',
  cf-cache-status: 'DYNAMIC',
  cf-ray: '84a27c9e07ea13cf-ORD',
  connection: 'keep-alive',
  content-length: '135',
  content-type: 'application/json',
  date: 'Tue, 23 Jan 2024 19:36:39 GMT',
  ratelimitbysize-limit: '2000000',
  ratelimitbysize-query-cost: '279',
  ratelimitbysize-remaining: '1999721',
  ratelimitbysize-reset: '21',
  server: 'cloudflare',
  x-kong-proxy-latency: '6',
  x-kong-request-id: '64be951a3b11464c35151500df299478',
  x-kong-upstream-latency: '10',
  x-ratelimitbysize-limit-minute: '2000000',
  x-ratelimitbysize-limit-month: '10000000000',
  x-ratelimitbysize-remaining-minute: '1999721',
  x-ratelimitbysize-remaining-month: '9999422542'
},
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
```

**Comment by mckaywrigley** [comment]
Double check that you have pulled and deployed the latest code updates.

I've confirmed that all models now work in Vercel with the latest api changes.
