### ISSUE TITLE
Vercel + Supabase hosted instance missing functionality and has relation errors

### ISSUE THREAD

**Issue by jgaltio** [mckaywrigley/chatbot-ui#1365]
Hi,

I hope this question isn't terribly naive, but after following the README.md instructions and filling out .env.local, is there a known reason why a Vercel hosted instance would still be missing all functionality (no OpenAI connection even with the key, etc.)?

Authentication with Supabase seems to work fine, but in the browser console there are other errors:

```
Failed to load resource: the server responded with a status of 404 ()
303-5568912817492aac.js:1  Uncaught (in promise) Error: relation "public.profiles" does not exist
    at i (303-5568912817492aac.js:1:6471)
    at async ea (layout-b3dc943fc331d2c8.js:1:4049)
    at async layout-b3dc943fc331d2c8.js:1:3456
```

Was I supposed to manually create the table(s) or something?

Thanks

**Comment by jgaltio** [comment]
@mckaywrigley Terribly sorry to bother and asking this with hesitation, but may I know why the issue was closed?

I just replicated the problem with another clean copy of the repo, new Supabase, and new Vercel, following the README.md instructions:

```
Error: relation "public.workspaces" does not exist
    at eN (/var/task/.next/server/app/[locale]/login/page.js:1:38294)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
    at async rg (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6309)
    at async rz (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24709)
    at async Y (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25417)
    at async Q.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1025)
    at async r3.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:507)
    at async r3.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:4780)
    at async r3.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5363)
```

**Comment by jgaltio** [comment]
OK, I've gotten to the bottom of this. There were a couple of factors in play, but at the heart of it, it comes from following steps 1 - 4 on MacOS before following the hosted instructions, resulting in a bad push of the database. It can be resolved with an improvement to the instructions. I will make a PR on the README.md.

**Comment by Onat-T** [comment]
Heya @jgaltio , I couldn't find a PR and I checked your fork. May I find out how you solved this please? I've had this for weeks now and all issues related to these are closed with no explanation.

**Comment by hack-r** [comment]
@Mahogany95 Yes, please see my prior comment - in a nutshell the README is a little wrong and tells you to go through certain steps that involve configuring the local supabase which is unnecessary for cloud supabase. You just need to ignore the local one, setup and link cloud. If you already had the problem it's easiest to start over clean from the beginning.
