### ISSUE TITLE
Can't login after a fresh install

### ISSUE THREAD

**Issue by ava8c** [mckaywrigley/chatbot-ui#1408]
Hi, this is the error when I access to login page. I followed the instructions "Local Quickstart".
![image](https://github.com/mckaywrigley/chatbot-ui/assets/16056544/29da1883-71b8-430d-8660-923bce3e95ed)

reply@Jarvis-M1 chatbot-ui % npm run chat  

> chatbot-ui@2.0.0 chat
> supabase start && npm run db-types && npm run dev

supabase start is already running.
Run supabase status to show status of local Supabase containers.

> chatbot-ui@2.0.0 db-types
> supabase gen types typescript --local > supabase/types.ts

(node:1) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

> chatbot-ui@2.0.0 dev
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env.local

> [PWA] Compile server
> [PWA] Compile server
> [PWA] Compile client (static)
> [PWA] Custom worker found: /Users/reply/Developer/repository/Reply/chatbot-ui/worker/index.js
> [PWA] Build custom worker: /Users/reply/Developer/repository/Reply/chatbot-ui/public/worker-development.js
> [PWA] Auto register service worker with: /Users/reply/Developer/repository/Reply/chatbot-ui/node_modules/next-pwa/register.js
> [PWA] Service worker: /Users/reply/Developer/repository/Reply/chatbot-ui/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Build in develop mode, cache and precache are mostly disabled. This means offline support is disabled, but you can continue developing other functions in service worker.
 ✓ Ready in 2.5s
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
 ○ Compiling /middleware ...
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.

 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
 ⚠ GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.

 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⨯ app/[locale]/login/page.tsx (45:12) @ Login
 ⨯ Error: JSON object requested, multiple (or no) rows returned
    at Login (./app/[locale]/login/page.tsx:51:19)
  43 |
  44 |     if (!homeWorkspace) {
> 45 |       throw new Error(error.message)
     |            ^
  46 |     }
  47 |
  48 |     return redirect(`/${homeWorkspace.id}/chat`)
 ⨯ app/[locale]/login/page.tsx (45:12) @ Login
 ⨯ Error: JSON object requested, multiple (or no) rows returned
    at Login (./app/[locale]/login/page.tsx:51:19)
digest: "4037407642"
  43 |
  44 |     if (!homeWorkspace) {
> 45 |       throw new Error(error.message)
     |            ^
  46 |     }
  47 |
  48 |     return redirect(`/${homeWorkspace.id}/chat`)

**Comment by ava8c** [comment]
Fixed cleaning browser data on localhost.
