### ISSUE TITLE
Hosted Vercel+Supabase Deployment crashing right after login

### ISSUE THREAD

**Issue by matanyall** [mckaywrigley/chatbot-ui#1411]
Hey, love the project, just running int a weird issue. Supabase shows everything correctly after doing the `supabase db push` but I get an error after actually going in that looks like this:

<img width="2032" alt="Screenshot 2024-02-08 at 10 59 12 AM" src="https://github.com/mckaywrigley/chatbot-ui/assets/28307422/91600990-907d-4803-9a74-0b70d27771c8">
and the logs in vercel implies that because the database is empty, nothing is being returned for the POST /login:

```
Error: JSON object requested, multiple (or no) rows returned
    at eN (/var/task/.next/server/app/[locale]/login/page.js:1:38294)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
    at async rg (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6309)
    at async rz (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24709)
    at async Y (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25417)
    at async Q.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1025)
    at async r3.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:507)
    at async r3.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:4780)
    at async r3.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5363)
```

Any Ideas on how to pre populate these tables or get some sort of new user flow would be appreciated, keep up the good work!

**Comment by matanyall** [comment]
To be clear, the user signin flow seems to work, and my user is in supabase

**Comment by digitaldesaster** [comment]
same problem here

**Comment by yesbhautik** [comment]
sir, no need to open issue with same topics. #1377

**Comment by yesbhautik** [comment]
Vercel will never work with current release. you can use another method, i have given solution. Also, you need help with servers/hosting of this, please let me know.

You can close the issue. 😄

**Comment by mckaywrigley** [comment]
Likely just need to make sure migrations are applied - I see this a lot from people
