### ISSUE TITLE
JSON object requested, multiple (or no) rows returned

### ISSUE THREAD

**Issue by Trapper4888** [mckaywrigley/chatbot-ui#1412]
After a fresh install on macos, I get this on login page:
```
 ⨯ app/[locale]/login/page.tsx (45:12) @ Login
 ⨯ Error: JSON object requested, multiple (or no) rows returned
    at Login (./app/[locale]/login/page.tsx:51:19)
  43 |
  44 |     if (!homeWorkspace) {
> 45 |       throw new Error(error.message)
     |            ^
  46 |     }
  47 |
  48 |     return redirect(`/${homeWorkspace.id}/chat`)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ app/[locale]/login/page.tsx (45:12) @ Login
 ⨯ Error: JSON object requested, multiple (or no) rows returned
    at Login (./app/[locale]/login/page.tsx:51:19)
  43 |
  44 |     if (!homeWorkspace) {
> 45 |       throw new Error(error.message)
     |            ^
  46 |     }
  47 |
  48 |     return redirect(`/${homeWorkspace.id}/chat`)
 ⨯ app/[locale]/login/page.tsx (45:12) @ Login
 ⨯ Error: JSON object requested, multiple (or no) rows returned
    at Login (./app/[locale]/login/page.tsx:51:19)
digest: "4037407642"
  43 |
  44 |     if (!homeWorkspace) {
> 45 |       throw new Error(error.message)
     |            ^
  46 |     }
  47 |
  48 |     return redirect(`/${homeWorkspace.id}/chat`)
```

I had the same error on my old install after an update. I've deleted all supabase containers, init it and did a `supabase db reset`, it changed nothing.

**Comment by kmdavis** [comment]
I also got this. on fresh install (today) there was no error, but after I did a db reset, this error popped up. in the supabase console, I can see that there is no workspace (no rows in any db table)

ah... it looks like I have an auth token, but no corresponding db rows

fixed by clearing my cookies and signing up again

**Comment by Trapper4888** [comment]
> I also got this. on fresh install (today) there was no error, but after I did a db reset, this error popped up. in the supabase console, I can see that there is no workspace (no rows in any db table)
> 
> ah... it looks like I have an auth token, but no corresponding db rows
> 
> fixed by clearing my cookies and signing up again

Removed cookies and it works, thx a lot!!!
