### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by joe-ercolino** [mckaywrigley/chatbot-ui#1461]
Hi 

I've followed the instructions, but when run the chat I've got the following error:

```
joe@MBP-von-Jose chatbot-ui % npm run chat 

> chatbot-ui@2.0.0 chat
> supabase start && npm run db-types && npm run dev

supabase start is already running.
Run supabase status to show status of local Supabase containers.

> chatbot-ui@2.0.0 db-types
> supabase gen types typescript --local > supabase/types.ts

(node:1) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

> chatbot-ui@2.0.0 dev
> next dev

/Users/joe/Documents/GitHub/chatbot-ui/node_modules/array-uniq/index.js:56
		module
		      

SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/Users/joe/Documents/GitHub/chatbot-ui/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/joe/Documents/GitHub/chatbot-ui/node_modules/del/node_modules/array-union/index.js:2:17)

Node.js v18.17.1

```

MacOS Sonoma 14.3.1, MacBook Pro Intel

Thanks in advanced.

**Comment by Belxz777** [comment]
Sup, to fix such problem try to delete your node_module  and after clear cache using 
```zsh
 npm cache clean --force
yarn cache clean
pnpm store prune
```
after that install all your packages back , if it doesnt work try to install newwer version of node
