### ISSUE TITLE
Vercel Deployment: Application error: a server-side exception has occurred (see the server logs for more information).  Digest: 1249433048

### ISSUE THREAD

**Issue by devsusholding** [mckaywrigley/chatbot-ui#1616]
Hello, I tried to deploy the Chatbot on Vercel following the instructions.

However once Vercel has compiled the code by browsing the page I get this error:

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1249433048

![immagine](https://github.com/mckaywrigley/chatbot-ui/assets/163929526/b1f342bb-946c-4194-bce6-6643dc960c4e)

By browsing the logs on Vercel I see this error:

```
Error: relation "public.workspaces" does not exist
    at e_ (/var/task/.next/server/app/[locale]/login/page.js:1:36987)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
    at async rg (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6309)
    at async rz (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24709)
    at async Y (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25417)
    at async Q.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1025)
    at async r3.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:507)
    at async r3.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:4780)
    at async r3.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5363)
```
    

    Am I missing something?

**Comment by haydenkong** [comment]
same, don't know why

**Comment by haydenkong** [comment]
I think it's related to #1617

**Comment by devsusholding** [comment]
> I think it's related to #1617

Correct, I got the same behaviour

**Comment by tim13246879** [comment]
If you're getting this error "Error: relation "public.workspaces" does not exist" it could be that your migrations have not been applied. Try running `npm run db-push` to apply the latest migrations. I ran into the same problem with a self-hosted instance and this resolved it.
