### ISSUE TITLE
Can't get past Step 3 in onboarding

### ISSUE THREAD

**Issue by Virtual-Educator** [mckaywrigley/chatbot-ui#1627]
Setup Step 3 not patching username to profile and bring up groq error. Can't get past Step 3 in onboarding.
       
PATCH https://###.supabase.co/rest/v1/profiles?id=###&select=* 400 (Bad Request)
(anonymous) @ 540-d1b2e7a956503158.js:6
l @ 540-d1b2e7a956503158.js:6
s @ 540-d1b2e7a956503158.js:6
layout-52ce4a71a24613c8.js:1 Uncaught (in promise) Error: Column 'groq_api_key' of relation 'profiles' does not exist
    at s (layout-52ce4a71a24613c8.js:1:9704)
    at async ei (page-f10d92243d41f947.js:1:10025)

Steps to recreate:
Visit app in incognito window.
Start Chatting>Click
Enter new email and Set Up.
Wait for email. click confirm link.
Step 1>Username accepted (can't change... and confusing for new users)
Step 2>Add API key (OpenAI for me)
Step 3>Press next. Nothing happens. Errors show in Inspect.

**Comment by Virtual-Educator** [comment]
SOLVED. Had to manually add the groq_api_key column to Profiles.
