### ISSUE TITLE
error - Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by c2w570063013** [mckaywrigley/chatbot-ui#43]
![tg_image_162084211](https://user-images.githubusercontent.com/18510054/226599015-fd8d04bb-4847-43a3-ac8f-6d26af91d7ea.jpeg)
This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.<anonymous>:5724:19)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.<anonymous>:5881:49)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.<anonymous>:6094:35)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.<anonymous>:6510:49)
    at __require (evalmachine.<anonymous>:14:50)
    at <unknown> (evalmachine.<anonymous>:11635:30)
    at requireFn (file:///Users/bobjames/code/chatgpt/chatbot-ui/node_modules/next/dist/compiled/edge-runtime/index.js:1:7079) {
  name: 'TypeError'
}
error - Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.<anonymous>:5724:19)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.<anonymous>:5881:49)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.<anonymous>:6094:35)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.<anonymous>:6510:49)
    at __require (evalmachine.<anonymous>:14:50)
    at <unknown> (evalmachine.<anonymous>:11635:30)
    at requireFn (file:///Users/bobjames/code/chatgpt/chatbot-ui/node_modules/next/dist/compiled/edge-runtime/index.js:1:7079) {
  name: 'TypeError'
}
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/18510054/226598773-c3d0bb4b-4961-4da3-8f55-93f2679c9599.png">

**Comment by c2w570063013** [comment]
Hi, what should I do to fix this issue?

**Comment by lh15** [comment]
I have the same error

**Comment by c2w570063013** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by c2w570063013** [comment]
solved, I just upgraded the node version, and it worked
