### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by UshiroNaka** [mckaywrigley/chatbot-ui#616]
This is output after running npm run dev

```
C:\Users\Hromium\chatbot-ui\node_modules\next\dist\cli\next-dev.js:362
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (C:\Users\Hromium\chatbot-ui\node_modules\next\dist\lib\commands.js:10:30)
    at Object.<anonymous> (C:\Users\Hromium\chatbot-ui\node_modules\next\dist\bin\next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ai-chatbot-starter@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ai-chatbot-starter@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hromium\AppData\Roaming\npm-cache\_logs\2023-04-20T07_36_45_989Z-debug.log
```

**Comment by UshiroNaka** [comment]
Solved. Should update Node version
