### ISSUE TITLE
bug when run Google search

### ISSUE THREAD

**Issue by forkyguo** [mckaywrigley/chatbot-ui#811]
run with docker

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Cannot read properties of undefined (reading 'map')
    at handler (/app/.next/server/pages/api/google.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:375:20)
    at async /app/node_modules/next/dist/server/base-server.js:157:99
TypeError: Cannot read properties of undefined (reading 'map')
    at handler (/app/.next/server/pages/api/google.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:375:20)
    at async /app/node_modules/next/dist/server/base-server.js:157:99

**Comment by liferadioat** [comment]
Same at my docker installation:
```
framework-73b8966a3c579ab0.js:9 TypeError: Cannot read properties of undefined (reading 'length')
    at index-0237305ee427e816.js:1:33615
    at ab (framework-73b8966a3c579ab0.js:9:60917)
    at ud (framework-73b8966a3c579ab0.js:9:72803)
    at us (framework-73b8966a3c579ab0.js:9:72009)
    at i (framework-73b8966a3c579ab0.js:9:122857)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
    at framework-73b8966a3c579ab0.js:9:98981
    at oF (framework-73b8966a3c579ab0.js:9:98988)
    at ox (framework-73b8966a3c579ab0.js:9:95740)
    at oS (framework-73b8966a3c579ab0.js:9:94295)
```

**Comment by eh2024** [comment]
same here 

023-07-17T06:25:36.260024055Z TypeError: Cannot read properties of undefined (reading '0')
2023-07-17T06:25:36.260058610Z     at handler (/app/.next/server/pages/api/google.js:144:32)
2023-07-17T06:25:36.260062958Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-17T06:25:36.260065613Z     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
2023-07-17T06:25:36.260069250Z     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
2023-07-17T06:25:36.260071394Z     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
2023-07-17T06:25:36.260074360Z     at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
2023-07-17T06:25:36.260078778Z     at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29)
2023-07-17T06:25:36.260085160Z     at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:375:20)
2023-07-17T06:25:36.260091301Z     at async /app/node_modules/next/dist/server/base-server.js:157:99

**Comment by shelltea** [comment]
Same problem, who can fix it?
